pybot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  prismatic_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: prismatic_joint
    pid: {p: 15.0, i: 1.0, d: 5.0}
  shoulder_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder
    pid: {p: 15.0, i: 1.0, d: 5.0}
  elbow_position_controller:
    type: effort_controllers/JointPositionController
    joint: elbow
    pid: {p: 15.0, i: 1.0, d: 5.0}


